source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftHistorian_Example', :exclusive => true do
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod "SwiftHistorian", :path => "../"
end

target 'SwiftHistorian_Tests', :exclusive => true do
pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod "SwiftHistorian", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
