source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftHistorian_Example', :exclusive => true do
  pod "SwiftHistorian", :git => "../"
end

target 'SwiftHistorian_Tests', :exclusive => true do
  pod "SwiftHistorian", :git => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
